channels:
- conda-forge
dependencies:
- python=3.11.5
- pip<=24.0
- pip:
  - mlflow==2.12.2
  - cffi==1.16.0
  - defusedxml==0.7.1
  - graphviz==0.20.3
  - lightgbm==4.3.0
  - matplotlib==3.8.4
  - pandas==2.2.2
  - psutil==5.9.8
  - pyarrow==15.0.2
  - scikit-learn==1.4.0
name: mlflow-env
